// Generated by CoffeeScript 1.4.0
var Thing;

module.exports = Thing = (function() {

  function Thing(result) {
    this.result = result;
  }

  Thing.prototype["do"] = function(duration, callback) {
    var _this = this;
    return setTimeout(function() {
      return callback(null, _this.result);
    }, duration);
  };

  return Thing;

})();
